server:
  port: 8001

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: shige951021.
    url: jdbc:mysql://146.56.246.141:33067/property?useUnicode=true&characterEncoding=utf8mb4&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
    hikari:
      minimum-idle: 3
      max-lifetime: 30000
      connection-test-query: select 1
      maximum-pool-size: 10
  application:
    name: system
  cloud:
    nacos:
      discovery:
        server-addr: 172.16.0.42:8848
  redis:
    database: 0
    jedis:
      pool:
        max-active: -8
        max-idle: 300
        max-wait: 5000
        min-idle: 5
    host: 132.232.89.144
    port: 6379
    password: sdzy@123
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/com/shige/proper/mapper/xml/*.xml
#  mapper-locations: classpath:/mapper/xml/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0